# Generated by Django 5.2.15 on 2026-09-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['workspace', 'is_global', 'archived_at'], name='pages_wiki_scope_idx'),
        ),
    ]
