# Generated by Django 5.2.15 on 2026-09-22 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_page_pages_wiki_scope_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo_props', models.JSONField(default=dict)),
                ('access', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collections', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Collection',
                'verbose_name_plural': 'Page Collections',
                'db_table': 'page_collections',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PageCollectionMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(5, 'View'), (10, 'Comment'), (15, 'Edit')], default=5)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='db.pagecollection')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collection_memberships', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collection_members', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Collection Member',
                'verbose_name_plural': 'Page Collection Members',
                'db_table': 'page_collection_members',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageCollectionPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_pages', to='db.pagecollection')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_pages', to='db.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collection_pages', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Collection Page',
                'verbose_name_plural': 'Page Collection Pages',
                'db_table': 'page_collection_pages',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='pagecollection',
            index=models.Index(fields=['workspace', 'sort_order'], name='page_collection_ws_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecollection',
            index=models.Index(fields=['workspace', 'access'], name='page_collection_ws_access_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('workspace',), name='page_collection_unique_default_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='pagecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='page_collection_unique_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='pagecollectionmember',
            index=models.Index(fields=['collection', 'member'], name='page_coll_member_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecollectionmember',
            index=models.Index(fields=['workspace', 'member'], name='page_coll_member_ws_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagecollectionmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('collection', 'member'), name='page_collection_member_unique_collection_member'),
        ),
        migrations.AddIndex(
            model_name='pagecollectionpage',
            index=models.Index(fields=['collection', 'sort_order'], name='page_coll_page_coll_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecollectionpage',
            index=models.Index(fields=['workspace', 'page'], name='page_coll_page_ws_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagecollectionpage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('page',), name='page_collection_page_unique_page'),
        ),
        migrations.AddConstraint(
            model_name='pagecollectionpage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('collection', 'page'), name='page_collection_page_unique_collection_page'),
        ),
    ]
