# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.15 on 2026-09-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_pagecollection_pagecollectionmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(5, 'View'), (10, 'Comment'), (15, 'Edit')], default=5)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_shares', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='db.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_shares', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Share',
                'verbose_name_plural': 'Page Shares',
                'db_table': 'page_shares',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='pageshare',
            index=models.Index(fields=['page', 'member'], name='page_share_page_member_idx'),
        ),
        migrations.AddIndex(
            model_name='pageshare',
            index=models.Index(fields=['workspace', 'member'], name='page_share_ws_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageshare',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('page', 'member'), name='page_share_unique_page_member'),
        ),
    ]
