# Generated by Django 5.2.15 on 2026-09-23 03:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_pagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCommentModeration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('hide', 'Hide'), ('unhide', 'Unhide')], max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Page Comment Moderation',
                'verbose_name_plural': 'Page Comment Moderations',
                'db_table': 'page_comment_moderations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'db_table': 'page_views',
                'ordering': ('-viewed_at',),
            },
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_page_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='hidden_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pagecomment',
            index=models.Index(fields=['page', 'is_hidden', 'created_at'], name='page_comment_page_hidden_idx'),
        ),
        migrations.AddField(
            model_name='pagecommentmoderation',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_comment_moderations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecommentmoderation',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_log', to='db.pagecomment'),
        ),
        migrations.AddField(
            model_name='pagecommentmoderation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagecommentmoderation',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_moderations', to='db.page'),
        ),
        migrations.AddField(
            model_name='pagecommentmoderation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagecommentmoderation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comment_moderations', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='db.pagecollection'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='db.page'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageview',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='pagecommentmoderation',
            index=models.Index(fields=['comment', 'created_at'], name='page_comment_mod_comment_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecommentmoderation',
            index=models.Index(fields=['page', 'created_at'], name='page_comment_mod_page_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page', 'viewed_at'], name='page_view_page_viewed_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['collection', 'viewed_at'], name='page_view_coll_viewed_idx'),
        ),
    ]
