# Generated by Django 5.2.15 on 2026-09-23 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0128_page_analytics_and_comment_moderation"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("page_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page.created", "Page Created"),
                            ("page.updated", "Page Updated"),
                            ("page.moved", "Page Moved"),
                            ("page.archived", "Page Archived"),
                            ("page.restored", "Page Restored"),
                            ("page.deleted", "Page Deleted"),
                            ("page.access_changed", "Page Access Changed"),
                            ("page.imported", "Page Imported"),
                            ("page.ai_edit", "Page AI Edit"),
                        ],
                        max_length=64,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Wiki Event",
                "verbose_name_plural": "Wiki Events",
                "db_table": "wiki_events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="wikievent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wikievent",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="wikievent",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AddField(
            model_name="wikievent",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiki_events",
                to="db.page",
            ),
        ),
        migrations.AddField(
            model_name="wikievent",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wiki_events",
                to="db.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="wikievent",
            index=models.Index(fields=["workspace", "created_at"], name="wiki_event_ws_created_idx"),
        ),
        migrations.AddIndex(
            model_name="wikievent",
            index=models.Index(fields=["workspace", "event_type", "created_at"], name="wiki_event_ws_type_idx"),
        ),
    ]
